{% set name = "async-retriever" %}
{% set version = "0.19.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/89/25/7e1e31dbe75ea867ce844b769ada515fc50883e2d632a3e6bfe363902003/async_retriever-{{ version }}.tar.gz
  sha256: 22da28f4861f4182240e2a598e93ac3d94af5c3692b566016ff228056267f15b

build:
  number: 0

outputs:
  - name: {{ name }}
    build:
      noarch: python
    script: build_base.sh
    requirements:
      host:
        - python {{ python_min }}
        - hatchling
        - hatch-vcs
        - pip
      run:
        - python >={{ python_min }}
        - aiofiles
        - aiodns
        - aiohttp-client-cache >=0.12.3
        - brotli
        - cytoolz
        - orjson

    test:
      imports:
        - async_retriever
      commands:
        - pip check
      requires:
        - pip
        - python {{ python_min }}

  - name: async_retriever
    build:
      noarch: python
    requirements:
      run:
        - {{ pin_subpackage(name, exact=True) }}
    test:
      requires:
        - python {{ python_min }}
      imports:
        - async_retriever

about:
  home: https://github.com/hyriver/async-retriever
  summary: High-level API for asynchronous requests with persistent caching.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - cheginit
