{% set name = "async-retriever" %}
{% set version = "0.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 29a8d8b9f3c2639a999d68d007c2ea0fd5cfe679c8c1937735b782bf6716b0d7

build:
  number: 0

outputs:
  - name: {{ name }}
    build:
      noarch: python
    script: build_base.sh
    requirements:
      host:
        - python {{ python_min }}
        - hatchling
        - hatch-vcs
        - pip
      run:
        - python >={{ python_min }}
        - aiodns
        - aiohttp-client-cache >=0.12.3
        - brotli
        - cytoolz
        - nest-asyncio
        - ujson

    test:
      imports:
        - async_retriever
      commands:
        - pip check
      requires:
        - pip

  - name: async_retriever
    build:
      noarch: python
    requirements:
      run:
        - {{ pin_subpackage(name, exact=True) }}
    test:
      requires:
        - python {{ python_min }}
      imports:
        - async_retriever

about:
  home: https://github.com/hyriver/async-retriever
  summary: High-level API for asynchronous requests with persistent caching.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - cheginit
